routes/web.php
<?php

use App\Http\Controllers\Admin\MessangerController;
use App\Http\Controllers\Admin\RulesController;
use App\Http\Controllers\Admin\SciensController;

use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\HelloController::class,'mainboard'])->name('main');

Route::get('/widget', function () {
    return view('main.pages.widget');
})->name('main.widget');

Route::get('/show_messenger/{publication}/{year}', [MessangerController::class, 'show_accept_messenger'])->name('show_messenger');

Route::resource('/messanger', MessangerController::class);


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'preventBack']], function () {
    Route::get('/', function () {
        return view('admin.layouts.index');
    })->name("admin.dashboard");
    Route::resource('/sciens', SciensController::class);
    Route::resource('/rules', RulesController::class);
    Route::get('/notifications', [UserController::class, 'notifications'])->name('user.notifications');
    Route::get('/success', [UserController::class, 'indexsuccess'])->name('user.success');
    Route::get('/timesuccess', [UserController::class, 'timesuccess'])->name('user.timesuccess');
    Route::get('/uploadfile/{article}', [UserController::class, 'uploadFile'])->name('user.uploadfile');
    Route::put('/uploadfilestore/{article}', [UserController::class, 'uploadFileStore'])->name('user.uploadfilestore');
    Route::resource('/maqolas', \App\Http\Controllers\Admin\MaqolaController::class);
    Route::resource('/direct', \App\Http\Controllers\Admin\DirectController::class);
});

Route::group(['prefix' => 'user', 'middleware' => ['auth', 'isUser', 'preventBack']], function () {
    Route::get('/',[\App\Http\Controllers\Auth\HelloController::class, 'userboard'])->name("user.dashboard")->middleware('verified');
    Route::get('user/setting', [\App\Http\Controllers\Auth\HelloController::class, 'setting'])->name('user.setting');
    Route::put('user/edit', [\App\Http\Controllers\Auth\HelloController::class, 'userEdit'])->name('user.edit');
    Route::get('/subscription', function () {
        return view('users.profil.subscription');
    })->name('user.subscription');
    Route::resource('/articles', UserController::class);
    Route::post('/journal/section', [UserController::class, 'get_directs'])->name('ajax.journal');

});

Route::middleware(['middleware' => 'preventBack'])->group(function () {
    Auth::routes([
        'verify'=>true
    ]);
});
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

resources/views/admin/article/create.blade.php
@extends('admin.layouts.master')
@section('title','Maqolaning navbatdagi sonini yaratish')
@section('content')
{{--    <div class="container mt-5">--}}
{{--        <div class="col-12 grid-margin stretch-card">--}}
{{--            <div class="card">--}}
{{--                <div class="card-body">--}}
{{--                    @if(session()->has('messageM'))--}}
{{--                        <div class="alert alert-danger">--}}
{{--                            {{ session()->get('messageM') }}--}}
{{--                        </div>--}}
{{--                    @endif--}}
{{--                    <h4 class="card-title">Maqola yuborish uchun qoida yaratish</h4>--}}

{{--                    <form action="{{route('maqolas.store')}}" method="post" class="forms-sample">--}}
{{--                        @csrf--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="publication">Maqolani nashri soni</label>--}}
{{--                            <input name="publication" type="number" class="form-control" id="publication">--}}
{{--                            @if($errors->has('publication'))--}}
{{--                                <span class="text-danger">{{ $errors->first('publication') }}</span>--}}
{{--                            @endif--}}
{{--                        </div>--}}

{{--                        <div class="form-group">--}}
{{--                            <label for="exampleInputName1">Maqolani boshlash vaqti</label>--}}
{{--                            <input name="start_date" type="date" class="form-control" id="exampleInputName1">--}}
{{--                            @if($errors->has('start_date'))--}}
{{--                                <span class="text-danger">{{ $errors->first('start_date') }}</span>--}}
{{--                            @endif--}}
{{--                        </div>--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="exampleInputName2">Maqolani tugash vaqti</label>--}}
{{--                            <input name="end_date" type="date" class="form-control" id="exampleInputName2">--}}
{{--                            @if($errors->has('end_date'))--}}
{{--                                <span class="text-danger">{{ $errors->first('end_date') }}</span>--}}
{{--                            @endif--}}
{{--                        </div>--}}
{{--                        <div class="form-group">--}}
{{--                            <label for="exampleInputName3">Maqolani chiqish vaqti</label>--}}
{{--                            <input name="show_date" type="date" class="form-control" id="exampleInputName3">--}}
{{--                            @if($errors->has('show_date'))--}}
{{--                                <span class="text-danger">{{ $errors->first('show_date') }}</span>--}}
{{--                            @endif--}}
{{--                        </div>--}}
{{--                        <input type="hidden" name="year" value="{{ date('Y') }}">--}}
{{--                        <button type="submit" class="btn btn-gradient-primary me-2">Qo'shish</button>--}}

{{--                    </form>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}



<div class="page-body">
    <div class="row">
        <div class="col-sm-12 m-auto mt-5">
            <div class="card">
                <div class="card-header">
                    <h4 class="card-title">Maqola yuborish uchun qoida yaratish</h4>
                </div>
                <div class="card-body">
                    @if(session()->has('messageM'))
                        <div class="alert alert-danger">
                            {{ session()->get('messageM') }}
                        </div>
                    @endif
                        <form action="{{route('maqolas.store')}}" method="post" class="forms-sample">
                            @csrf
                            <div class="mb-3">
                                <label for="publication">Maqolani nashri soni</label>
                                <input name="publication" type="number" class="form-control" id="publication">
                                @if($errors->has('publication'))
                                    <span class="text-danger">{{ $errors->first('publication') }}</span>
                                @endif
                            </div>

                            <div class="mb-3">
                                <label for="exampleInputName1">Maqolaga qabul boshlanish vaqti</label>
                                <input name="start_date" type="date" class="form-control" id="exampleInputName1">
                                @if($errors->has('start_date'))
                                    <span class="text-danger">{{ $errors->first('start_date') }}</span>
                                @endif
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputName2">Maqolaga qabul tugash vaqti</label>
                                <input name="end_date" type="date" class="form-control" id="exampleInputName2">
                                @if($errors->has('end_date'))
                                    <span class="text-danger">{{ $errors->first('end_date') }}</span>
                                @endif
                            </div>
                            <div class="mb-3">
                                <label for="exampleInputName3">Maqolani jurnalga chop qilinish vaqti</label>
                                <input name="show_date" type="date" class="form-control" id="exampleInputName3">
                                @if($errors->has('show_date'))
                                    <span class="text-danger">{{ $errors->first('show_date') }}</span>
                                @endif
                            </div>
                            <input type="hidden" name="year" value="{{ date('Y') }}">
                            <div class="mb-3">
                                <input type="submit" class="btn btn-primary" value="Qo'shish"/>
                            </div>

                        </form>
                </div>

            </div>
        </div>
    </div>

</div>
@endsection

resources/views/admin/article/edit.blade.php
@extends('admin.layouts.master')
@section('title','Maqolaning navbatdagi sonini tahrirlash')
@section('content')
    <div class="page-body">
        <div class="row">
            <div class="col-sm-12 m-auto mt-5">
                <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Maqola yuborish uchun qoida yaratish</h4>

                    <form action="{{route('maqolas.update', $maqola)}}" method="post" class="forms-sample">
                        @csrf
                        @method('PUT')
                        <div class="form-group mb-3">
                            <label for="publication">Maqolani nashri soni</label>
                            <input name="publication" type="number" class="form-control" id="publication" value="{{ $maqola->publication }}">
                            @if($errors->has('publication'))
                                <span class="text-danger">{{ $errors->first('publication') }}</span>
                            @endif
                        </div>
                        <div class="form-group mb-3">
                            <label for="exampleInputName1">Maqolani boshlash vaqti</label>
                            <input name="start_date" type="date" class="form-control" id="exampleInputName1" value="{{ $maqola->start_date }}">
                            @if($errors->has('start_date'))
                                <span class="text-danger">{{ $errors->first('start_date') }}</span>
                            @endif
                        </div>
                        <div class="form-group mb-3">
                            <label for="exampleInputName2">Maqolani tugash vaqti</label>
                            <input name="end_date" type="date" class="form-control" id="exampleInputName2" value="{{ $maqola->end_date }}">
                            @if($errors->has('end_date'))
                                <span class="text-danger">{{ $errors->first('end_date') }}</span>
                            @endif
                        </div>
                        <div class="form-group mb-3">
                            <label for="exampleInputName3">Maqolani chiqish vaqti</label>
                            <input name="show_date" type="date" class="form-control" id="exampleInputName3" value="{{ $maqola->show_date }}">
                            @if($errors->has('show_date'))
                                <span class="text-danger">{{ $errors->first('show_date') }}</span>
                            @endif
                        </div>
                        <input type="hidden" name="year" value="{{ date('Y') }}">

                        <div class="mb-3">
                            <button class="btn btn-primary" type="submit">Vaqtlarni o'zgartirish</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/article/index.blade.php
@extends('admin.layouts.master')
@section('title','Maqola sonlarini tahrirlash')
@section('content')

    {{--    <div class="container mt-5">--}}

    {{--        <div class="col-lg-12 grid-margin stretch-card">--}}

    {{--            <div class="card" style="padding: 20px;">--}}
    {{--                @if(\Illuminate\Support\Facades\Session::get('success'))--}}
    {{--                    <div class="alert alert-success">--}}
    {{--                        {{\Illuminate\Support\Facades\Session::get('success')}}--}}
    {{--                    </div>--}}
    {{--                @endif--}}
    {{--                <td class="card-body">--}}
    {{--                    @if(session()->has('messageM'))--}}
    {{--                        <div class="alert alert-danger">--}}
    {{--                            {{ session()->get('messageM') }}--}}
    {{--                        </div>--}}
    {{--                    @endif--}}
    {{--                    <h4 class="card-title">Maqolalar soni jadvali</h4>--}}
    {{--                    <br>--}}
    {{--                    <table class="table">--}}
    {{--                        <thead>--}}
    {{--                        <tr>--}}

    {{--                            <th>--}}
    {{--                                №--}}
    {{--                            </th>--}}
    {{--                            <th>--}}
    {{--                                Nashr soni--}}
    {{--                            </th>--}}
    {{--                            <th>--}}
    {{--                                Boshlanish vaqti--}}
    {{--                            </th>--}}
    {{--                            <th>--}}
    {{--                                Tugash vaqti--}}
    {{--                            </th>--}}
    {{--                            <th>--}}
    {{--                                Chiqish vaqti--}}
    {{--                            </th>--}}

    {{--                            <th>--}}
    {{--                                Yili--}}
    {{--                            </th>--}}

    {{--                            <th>--}}
    {{--                                Tahrirlash--}}
    {{--                            </th>--}}


    {{--                        </tr>--}}

    {{--                        </thead>--}}

    {{--                        <tbody>--}}
{{--                            @foreach($maqolas as $maqola)--}}
{{--                                <tr>--}}

{{--                                    <td>--}}
{{--                                        {{$loop->index+1}}--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        {{$maqola->publication}}--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        {{$maqola->start_date}}--}}
{{--                                    </td>--}}
{{--                                    <td style="text-align: justify">--}}
{{--                                        {{$maqola->end_date}}--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        {{ $maqola->show_date }}--}}
{{--                                    </td>--}}

{{--                                    <td>--}}
{{--                                        {{ $maqola->year }}--}}
{{--                                    </td>--}}
{{--                                    <td class="h-25 d-flex align-content-center">--}}
{{--                                        <a href="{{ route('maqolas.edit', $maqola) }}" class="d-flex btn btn-primary"--}}
{{--                                           style="margin-right: 15px;"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;O'zgartirish</a><br>--}}
{{--                                        <form class="d-flex" action="{{route('maqolas.destroy', $maqola) }}" method="POST">--}}
{{--                                            @csrf--}}
{{--                                            @method('DELETE')--}}
{{--                                            <button type="submit" class="d-flex btn btn-danger" data-toggle="tooltip"--}}
{{--                                                    title='Delete'><i class="far fa-trash-alt"></i>&nbsp;&nbsp;O'chirish--}}
{{--                                            </button>--}}
{{--                                        </form>--}}
{{--                                    </td>--}}


{{--                                </tr>--}}
{{--                            @endforeach--}}
    {{--                        </tbody>--}}
    {{--                    </table>--}}
    {{--            </div>--}}
    {{--        </div>--}}
    {{--    </div>--}}
    {{--    </div>--}}

    <div class="page-body pt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        @if(\Illuminate\Support\Facades\Session::get('success'))
                            <div class="alert alert-success">
                                {{\Illuminate\Support\Facades\Session::get('success')}}
                            </div>
                        @endif
                        <div class="card-header">
                            <h4 class="card-title">Maqolalar soni jadvali</h4>
                        </div>
                        <div class="table-responsive">
                            @if(session()->has('messageM'))
                                <div class="alert alert-danger">
                                    {{ session()->get('messageM') }}
                                </div>
                            @endif
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>
                                        №
                                    </th>
                                    <th>
                                        Nashr soni
                                    </th>
                                    <th>
                                        Boshlanish vaqti
                                    </th>
                                    <th>
                                        Tugash vaqti
                                    </th>
                                    <th>
                                        Chiqish vaqti
                                    </th>

                                    <th>
                                        Yili
                                    </th>

                                    <th>
                                        Tahrirlash
                                    </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($maqolas as $maqola)
                                    <tr>

                                        <td>
                                            {{$loop->index+1}}
                                        </td>
                                        <td>
                                            {{$maqola->publication}}
                                        </td>
                                        <td>
                                            {{$maqola->start_date}}
                                        </td>
                                        <td style="text-align: justify">
                                            {{$maqola->end_date}}
                                        </td>
                                        <td>
                                            {{ $maqola->show_date }}
                                        </td>

                                        <td>
                                            {{ $maqola->year }}
                                        </td>
                                        <td class="d-flex align-content-center">
                                            <a href="{{ route('maqolas.edit', $maqola) }}" class="d-inline-block btn btn-primary"
                                               style="margin-right: 10px;"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;O'zgartirish</a>
                                            <form class="d-inline-block" action="{{route('maqolas.destroy', $maqola) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="d-flex btn btn-danger" data-toggle="tooltip"
                                                        title='Delete'><i class="far fa-trash-alt"></i>&nbsp;&nbsp;O'chirish
                                                </button>
                                            </form>
                                        </td>


                                    </tr>
                                @endforeach

                                </tbody>
                            </table>
                            {{--<div>{{ ($sciens->count() > 0) ? $sciens->links() : '' }}</div>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@push('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>
    <script type="text/javascript">

        $('.show_confirm').click(function (event) {
            var form = $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Siz maqolaning navbatdagi sonini o\'chirmoqchimisiz?`,

                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush