routes/web.php
<?php

use App\Http\Controllers\Admin\MessangerController;
use App\Http\Controllers\Admin\RulesController;
use App\Http\Controllers\Admin\SciensController;

use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\HelloController::class,'mainboard'])->name('main');

Route::get('/widget', function () {
    return view('main.pages.widget');
})->name('main.widget');

Route::get('/show_messenger/{publication}/{year}', [MessangerController::class, 'show_accept_messenger'])->name('show_messenger');

Route::resource('/messanger', MessangerController::class);


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'preventBack']], function () {
    Route::get('/', function () {
        return view('admin.layouts.index');
    })->name("admin.dashboard");
    Route::resource('/sciens', SciensController::class);
    Route::resource('/rules', RulesController::class);
    Route::get('/notifications', [UserController::class, 'notifications'])->name('user.notifications');
    Route::get('/success', [UserController::class, 'indexsuccess'])->name('user.success');
    Route::get('/timesuccess', [UserController::class, 'timesuccess'])->name('user.timesuccess');
    Route::get('/uploadfile/{article}', [UserController::class, 'uploadFile'])->name('user.uploadfile');
    Route::put('/uploadfilestore/{article}', [UserController::class, 'uploadFileStore'])->name('user.uploadfilestore');
    Route::resource('/maqolas', \App\Http\Controllers\Admin\MaqolaController::class);
    Route::resource('/direct', \App\Http\Controllers\Admin\DirectController::class);
});

Route::group(['prefix' => 'user', 'middleware' => ['auth', 'isUser', 'preventBack']], function () {
    Route::get('/',[\App\Http\Controllers\Auth\HelloController::class, 'userboard'])->name("user.dashboard")->middleware('verified');
    Route::get('user/setting', [\App\Http\Controllers\Auth\HelloController::class, 'setting'])->name('user.setting');
    Route::put('user/edit', [\App\Http\Controllers\Auth\HelloController::class, 'userEdit'])->name('user.edit');
    Route::get('/subscription', function () {
        return view('users.profil.subscription');
    })->name('user.subscription');
    Route::resource('/articles', UserController::class);
    Route::post('/journal/section', [UserController::class, 'get_directs'])->name('ajax.journal');

});

Route::middleware(['middleware' => 'preventBack'])->group(function () {
    Auth::routes([
        'verify'=>true
    ]);
});
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

resources/views/admin/layouts/index.blade.php
@extends('admin.layouts.master')
@section('title','Admin panel')
@section('content')

@endsection

resources/views/admin/layouts/master.blade.php
{{--<!DOCTYPE html>--}}
{{--<html lang="en">--}}
{{--<head>--}}

{{--    <meta charset="utf-8">--}}
{{--    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">--}}
{{--    <title>@yield('title')</title>--}}
{{--    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" integrity="sha512-9usAa10IRO0HhonpyAIVpjrylPvoDwiPUiKdWk5t3PyolY1cOd4DSE0Ga+ri4AuTroPR5aQvXU9xC6qOPnzFeg==" crossorigin="anonymous" referrerpolicy="no-referrer" />--}}
{{--    <link rel="stylesheet" href="{{asset('auth/assets/vendors/mdi/css/materialdesignicons.min.css')}}">--}}
{{--    <link rel="stylesheet" href="{{asset('auth/assets/vendors/css/vendor.bundle.base.css')}}">--}}

{{--    <link rel="stylesheet" href="{{asset('auth/assets/css/style.css')}}">--}}

{{--    <link rel="shortcut icon" href="{{asset('auth/assets/images/favicon.ico')}}" />--}}
{{--</head>--}}
{{--<body style="background: #efefef">--}}
{{--<div class="container-scroller">--}}

{{--    @include('admin.layouts.navbar')--}}

{{--    <div class="container-fluid page-body-wrapper">--}}

{{--        @include('admin.layouts.side')--}}

{{--        <div class="main-panel">--}}

{{--            @yield('content')--}}

{{--        </div>--}}

{{--    </div>--}}

{{--</div>--}}

{{--<script src="{{asset('auth/assets/vendors/js/vendor.bundle.base.js')}}"></script>--}}

{{--<script src="{{asset('auth/assets/vendors/chart.js/Chart.min.js')}}"></script>--}}
{{--<script src="{{asset('auth/assets/js/jquery.cookie.js')}}" type="text/javascript"></script>--}}

{{--<script src="{{asset('auth/assets/js/off-canvas.js')}}"></script>--}}
{{--<script src="{{asset('auth/assets/js/hoverable-collapse.js')}}"></script>--}}
{{--<script src="{{asset('auth/assets/js/misc.js')}}"></script>--}}

{{--<script src="{{asset('auth/assets/js/dashboard.js')}}"></script>--}}
{{--<script src="{{asset('auth/assets/js/todolist.js')}}"></script>--}}
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/2.1.0/sweetalert.min.js"></script>--}}
{{--@include('sweetalert::alert')--}}
{{--@stack('script')--}}
{{--</body>--}}
{{--</html>--}}
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Cuba admin is super flexible, powerful, clean &amp; modern responsive bootstrap 5 admin template with unlimited possibilities.">
    <meta name="keywords" content="admin template, Cuba admin template, dashboard template, flat admin template, responsive admin template, web app">
    <meta name="author" content="pixelstrap">
    <link rel="icon" href="{{asset('users//assets/images/favicon.png')}}" type="image/x-icon">
    <link rel="shortcut icon" href="{{asset('users/assets/images/favicon.png')}}" type="image/x-icon">
    <title>@yield('title')</title>

    <link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i&amp;display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/font-awesome.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/icofont.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/themify.css')}}">
    <!-- Flag icon-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/flag-icon.css')}}">
    <!-- Feather icon-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/feather-icon.css')}}">
    <!-- Plugins css start-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/scrollbar.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/animate.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/chartist.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/date-picker.css')}}">

    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/select2.css')}}">
    <!-- Plugins css Ends-->
    <!-- Bootstrap css-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/vendors/bootstrap.css')}}">
    <!-- App css-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/style.css')}}">
    <link id="color" rel="stylesheet" href="{{asset('users/assets/css/color-1.css')}}" media="screen">
    <!-- Responsive css-->
    <link rel="stylesheet" type="text/css" href="{{asset('users/assets/css/responsive.css')}}">
</head>
<body onload="startTime()">
<div class="loader-wrapper">
    <div class="loader-index"><span></span></div>
    <svg>
        <defs></defs>
        <filter id="goo">
            <fegaussianblur in="SourceGraphic" stddeviation="11" result="blur"></fegaussianblur>
            <fecolormatrix in="blur" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 19 -9" result="goo"> </fecolormatrix>
        </filter>
    </svg>
</div>

<div class="tap-top"><i data-feather="chevrons-up"></i></div>

<div class="page-wrapper compact-wrapper" id="pageWrapper">

    @include('admin.layouts.navbar')

    <div class="page-body-wrapper">

        @include('admin.layouts.side')

        @yield('content')

{{--        @include('admin.layouts.footer')--}}
    </div>
</div>

<script src="{{asset('users/assets/js/jquery-3.5.1.min.js')}}"></script>
<!-- Bootstrap js-->
<script src="{{asset('users/assets/js/bootstrap/bootstrap.bundle.min.js')}}"></script>
<!-- feather icon js-->
<script src="{{asset('users/assets/js/icons/feather-icon/feather.min.js')}}"></script>
<script src="{{asset('users/assets/js/icons/feather-icon/feather-icon.js')}}"></script>
<!-- scrollbar js-->
<script src="{{asset('users/assets/js/scrollbar/simplebar.js')}}"></script>
<script src="{{asset('users/assets/js/scrollbar/custom.js')}}"></script>
<!-- Sidebar jquery-->
<script src="{{asset('users/assets/js/config.js')}}"></script>
<!-- Plugins JS start-->
<script src="{{asset('users/assets/js/sidebar-menu.js')}}"></script>
<script src="{{asset('users/assets/js/chart/chartist/chartist.js')}}"></script>
<script src="{{asset('users/assets/js/chart/chartist/chartist-plugin-tooltip.js')}}"></script>
<script src="{{asset('users/assets/js/chart/knob/knob.min.js')}}"></script>
<script src="{{asset('users/assets/js/chart/knob/knob-chart.js')}}"></script>
<script src="{{asset('users/assets/js/chart/apex-chart/apex-chart.js')}}"></script>
<script src="{{asset('users/assets/js/chart/apex-chart/stock-prices.js')}}"></script>
<script src="{{asset('users/assets/js/notify/bootstrap-notify.min.js')}}"></script>
<script src="{{asset('users/assets/js/dashboard/default.js')}}"></script>
<script src="{{asset('users/assets/js/notify/index.js')}}"></script>
<script src="{{asset('users/assets/js/datepicker/date-picker/datepicker.js')}}"></script>
<script src="{{asset('users/assets/js/datepicker/date-picker/datepicker.en.js')}}"></script>
<script src="{{asset('users/assets/js/datepicker/date-picker/datepicker.custom.js')}}"></script>
<script src="{{asset('users/assets/js/typeahead/handlebars.js')}}"></script>
<script src="{{asset('users/assets/js/typeahead/typeahead.bundle.js')}}"></script>
<script src="{{asset('users/assets/js/typeahead/typeahead.custom.js')}}"></script>
<script src="{{asset('users/assets/js/typeahead-search/handlebars.js')}}"></script>
<script src="{{asset('users/assets/js/typeahead-search/typeahead-custom.js')}}"></script>
<script src="{{asset('users/assets/js/select2/select2.full.min.js')}}"></script>
<script src="{{asset('users/assets/js/select2/select2-custom.js')}}"></script>
<!-- Plugins JS Ends-->
<!-- Theme js-->
<script src="{{asset('users/assets/js/script.js')}}"></script>
<script src="{{asset('users/assets/js/theme-customizer/customizer.js')}}"></script>
@stack('scripts')
<!-- login js-->
<!-- Plugin used-->
</body>
</html>

resources/views/admin/layouts/side.blade.php
{{--{{session_start()}}--}}
{{--<nav class="sidebar sidebar-offcanvas" id="sidebar">--}}
{{--    <ul class="nav">--}}
{{--        <li class="nav-item nav-profile">--}}
{{--            <a href="#" class="nav-link">--}}
{{--                <div class="nav-profile-image">--}}
{{--                    <img src="{{asset('auth/assets/images/faces/face1.jpg')}}" alt="profile">--}}
{{--                    <span class="login-status online"></span>--}}
{{--                    <!--change to offline or busy as needed-->--}}
{{--                </div>--}}
{{--                <div class="nav-profile-text d-flex flex-column">--}}
{{--                    <span class="font-weight-bold mb-2">{{$ism}}</span>--}}
{{--                    <span class="font-weight-bold mb-2">{{\Illuminate\Support\Facades\Auth::user()->name." ".\Illuminate\Support\Facades\Auth::user()->lname}}</span>--}}
{{--                    <span class="text-secondary text-small">Project Manager</span>--}}
{{--                </div>--}}
{{--                <i class="mdi mdi-bookmark-check text-success nav-profile-badge"></i>--}}
{{--            </a>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" href="{{route('admin.dashboard')}}">--}}
{{--                <span class="menu-title">Dashboard</span>--}}
{{--                <i class="mdi mdi-home menu-icon"></i>--}}
{{--            </a>--}}
{{--        </li>--}}
{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-bs-toggle="collapse" href="#ui-basic" aria-expanded="false" aria-controls="ui-basic">--}}
{{--                <span class="menu-title">Fan yo'nalishi</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--                <i class="mdi mdi mdi-briefcase menu-icon"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="ui-basic">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('sciens.create')}}">Yo'nalish qo'shish</a></li>--}}

{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('sciens.index')}}">Yo'nalishlar</a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}

{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-bs-toggle="collapse" href="#ui-rules" aria-expanded="false" aria-controls="ui-rules">--}}
{{--                <span class="menu-title">Qoidalar</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--                <i class="mdi mdi mdi-script menu-icon"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="ui-rules">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('rules.create')}}">Qoida qo'shish</a></li>--}}

{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('rules.index')}}">Qoida tahrirlash</a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}

{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-bs-toggle="collapse" href="#ui-rules_3" aria-expanded="false" aria-controls="ui-rules_3">--}}
{{--                <span class="menu-title">Maqolalar</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--                <i class="mdi mdi mdi-script menu-icon"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="ui-rules_3">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('user.success')}}">Tasdiqlangan maqolalar</a></li>--}}

{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('user.timesuccess')}}">vaqt oraliqdagi</a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}

{{--        <li class="nav-item">--}}
{{--            <a class="nav-link" data-bs-toggle="collapse" href="#ui-rules2" aria-expanded="false" aria-controls="ui-basic">--}}
{{--                <span class="menu-title">Maqolaning navbatdagi<br> soni</span>--}}
{{--                <i class="menu-arrow"></i>--}}
{{--                <i class="mdi mdi mdi-script menu-icon"></i>--}}
{{--            </a>--}}
{{--            <div class="collapse" id="ui-rules2">--}}
{{--                <ul class="nav flex-column sub-menu">--}}
{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('maqolas.create')}}">Navbatdagi sonni <br> qo'shish</a></li>--}}

{{--                    <li class="nav-item"> <a class="nav-link" href="{{route('maqolas.index')}}">Navbatdagi sonlar</a></li>--}}
{{--                </ul>--}}
{{--            </div>--}}
{{--        </li>--}}

{{--    </ul>--}}
{{--</nav>--}}

<div class="sidebar-wrapper">
    <div>
        <div class="logo-wrapper"><a href="{{route('user.dashboard')}}"><img class="img-fluid for-light" src="{{asset('users/assets/images/logo/logo.png')}}" alt=""><img class="img-fluid for-dark" src="{{asset('users/assets/images/logo/logo_dark.png')}}" alt=""></a>
            <div class="back-btn"><i class="fa fa-angle-left"></i></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
        </div>
        <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('users/assets/images/logo/logo-icon.png')}}" alt=""></a></div>
        <nav class="sidebar-main">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="sidebar-menu">
                <ul class="sidebar-links" id="simple-bar">
                    <li class="back-btn"><a href="index.html"><img class="img-fluid" src="{{asset('users/assets/images/logo/logo-icon.png')}}" alt=""></a>
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">--}}
                        <div>
                            <h6 class="">Mjournal</h6>
                            <p class="">Buxoro Davlat Universiteti</p>
                        </div>
                    </li>

                    <li class="sidebar-list">
{{--                        <label class="badge badge-danger">Yangi</label>--}}
                        <a class="sidebar-link sidebar-title" href="#">
                            <i data-feather="briefcase"></i>
                            <span>Jurnallar</span></a>
                        <ul class="sidebar-submenu {{(request()->is('admin/sciens/create') || request()->is('admin/sciens') || request()->is('admin/sciens/*/edit')) ? 'd-block' : ''}}">
                            <li><a style="color: {{request()->is('admin/sciens/create') ? '#7366ff' : ''}}" href="{{route('sciens.create')}}">Jurnal qo'shish</a></li>
                            <li><a style="color: {{( request()->is('admin/sciens') || request()->is('admin/sciens/*/edit') ) ? '#7366ff' : ''}}" href="{{route('sciens.index')}}">Jurnal ko'rish</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
                        <a class="sidebar-link sidebar-title" href="#">
                            <i data-feather="grid"></i>
                            <span>Yo'nalishlar</span></a>
                        <ul class="sidebar-submenu {{(request()->is('admin/direct/create') || request()->is('admin/direct')) ? 'd-block' : ''}}">
                            <li><a style="color: {{request()->is('admin/direct/create') ? '#7366ff' : ''}}" href="{{route('direct.create')}}">Yo'nalish qo'shish</a></li>
                            <li><a style="color: {{request()->is('admin/direct') ? '#7366ff' : ''}}" href="{{route('direct.index')}}">Yo'nalish ko'rish</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
{{--                        <label class="badge badge-danger">Yangi</label>--}}
                        <a class="sidebar-link sidebar-title" href="#">
                            <i data-feather="bookmark"></i>
                            <span>Qoidalar</span>
                        </a>
                        <ul class="sidebar-submenu {{(request()->is('admin/rules/create') || request()->is('admin/rules')) ? 'd-block' : ''}}">
                            <li><a style="color: {{request()->is('admin/rules/create') ? '#7366ff' : ''}}" href="{{route('rules.create')}}">Qoida qo'shish</a></li>
                            <li><a style="color: {{request()->is('admin/rules') ? '#7366ff' : ''}}" href="{{route('rules.index')}}">Qoida tahrirlash</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
                        <label class="badge badge-danger">Yangi</label>
                        <a class="sidebar-link sidebar-title" href="#">
                            <i data-feather="file-text"></i>
                            <span>Maqolalar</span>
                        </a>
                        <ul class="sidebar-submenu {{(request()->is('admin/timesuccess') || request()->is('admin/success')) ? 'd-block' : ''}}">
                            <li><a style="color: {{request()->is('admin/success') ? '#7366ff' : ''}}" href="{{route('user.success')}}">Tasdiqlangan maqolalar</a></li>
                            <li><a style="color: {{request()->is('admin/timesuccess') ? '#7366ff' : ''}}" href="{{route('user.timesuccess')}}">Vaqt oraliqdagi</a></li>
                        </ul>
                    </li>

                    <li class="sidebar-list">
{{--                        <label class="badge badge-danger">Yangi</label>--}}
                        <a class="sidebar-link sidebar-title" href="#">
                            <i data-feather="clock"></i>
                            <span>Maqola soni</span>
                        </a>
                        <ul class="sidebar-submenu {{(request()->is('admin/maqolas/create') || request()->is('admin/maqolas') || request()->is('admin/maqolas/*/edit')) ? 'd-block' : ''}}">
                            <li><a style="color: {{request()->is('admin/maqolas/create') ? '#7366ff' : ''}}" href="{{route('maqolas.create')}}">Yangi son</a></li>
                            <li><a style="color: {{(request()->is('admin/maqolas') || request()->is('admin/maqolas/*/edit')) ? '#7366ff' : ''}}" href="{{route('maqolas.index')}}">Navbatdagi sonlar</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </nav>
    </div>
</div>