routes/web.php
<?php

use App\Http\Controllers\Admin\MessangerController;
use App\Http\Controllers\Admin\RulesController;
use App\Http\Controllers\Admin\SciensController;

use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\HelloController::class,'mainboard'])->name('main');

Route::get('/widget', function () {
    return view('main.pages.widget');
})->name('main.widget');

Route::get('/show_messenger/{publication}/{year}', [MessangerController::class, 'show_accept_messenger'])->name('show_messenger');

Route::resource('/messanger', MessangerController::class);


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'preventBack']], function () {
    Route::get('/', function () {
        return view('admin.layouts.index');
    })->name("admin.dashboard");
    Route::resource('/sciens', SciensController::class);
    Route::resource('/rules', RulesController::class);
    Route::get('/notifications', [UserController::class, 'notifications'])->name('user.notifications');
    Route::get('/success', [UserController::class, 'indexsuccess'])->name('user.success');
    Route::get('/timesuccess', [UserController::class, 'timesuccess'])->name('user.timesuccess');
    Route::get('/uploadfile/{article}', [UserController::class, 'uploadFile'])->name('user.uploadfile');
    Route::put('/uploadfilestore/{article}', [UserController::class, 'uploadFileStore'])->name('user.uploadfilestore');
    Route::resource('/maqolas', \App\Http\Controllers\Admin\MaqolaController::class);
    Route::resource('/direct', \App\Http\Controllers\Admin\DirectController::class);
});

Route::group(['prefix' => 'user', 'middleware' => ['auth', 'isUser', 'preventBack']], function () {
    Route::get('/',[\App\Http\Controllers\Auth\HelloController::class, 'userboard'])->name("user.dashboard")->middleware('verified');
    Route::get('user/setting', [\App\Http\Controllers\Auth\HelloController::class, 'setting'])->name('user.setting');
    Route::put('user/edit', [\App\Http\Controllers\Auth\HelloController::class, 'userEdit'])->name('user.edit');
    Route::get('/subscription', function () {
        return view('users.profil.subscription');
    })->name('user.subscription');
    Route::resource('/articles', UserController::class);
    Route::post('/journal/section', [UserController::class, 'get_directs'])->name('ajax.journal');

});

Route::middleware(['middleware' => 'preventBack'])->group(function () {
    Auth::routes([
        'verify'=>true
    ]);
});
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

app/Http/Controllers/Admin/SciensController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Domain\Sciens\Actions\SciensActions;
use App\Domain\Sciens\Actions\UpdateSciensActions;
use App\Domain\Sciens\DTO\SciensDTO;
use App\Domain\Sciens\DTO\UpdateSciensDTO;
use App\Domain\Sciens\Models\Scien;
use App\Domain\Sciens\Repositories\SciensRepositories;
use App\Domain\Sciens\Requests\SciensRequests;
use App\Domain\Sciens\Requests\UpdateSciensRequests;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Session;
use RealRashid\SweetAlert\Facades\Alert;

class SciensController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index(SciensRepositories $repositories)
    {

        $sciens = $repositories->getAll();
        return view('admin.sciens.index', compact('sciens'));


    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function create()
    {

        return view('admin.sciens.create');

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(SciensRequests $requests, SciensActions $actions)
    {

        try {
            $dto = SciensDTO::fromArray($requests->all());
            $actions->execute($dto);
        } catch (\Exception $exception) {
            return redirect()->back();
        }
        return redirect()->route('sciens.index');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param Scien $scien
     */
    public function edit(Scien $scien)
    {

        return view('admin.sciens.edit', compact('scien'));

    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateSciensActions $actions, UpdateSciensRequests $requests, Scien $scien)
    {

        try {
            $requests->merge([
                'scien' => $scien
            ]);
            $dto = UpdateSciensDTO::fromArray($requests->all());
            $actions->execute($dto);
        } catch (\Exception $exception) {

            return redirect()->back();
        }

        return redirect()->route('sciens.index')->with('success', 'Siz yo\'nalishni muvofaqqiyatli tahrirladingiz');

    }

    /**
     * @param Scien $scien
     */
    public function destroy(Scien $scien)
    {

        $scien->delete();
        Alert::success($scien->sciensName, 'Yo\'nalishi o\'chirildi!');
        return redirect()->back();

    }
}

resources/views/admin/sciens/create.blade.php
@extends('admin.layouts.master')
@section('title', 'Yo\'nalish qo\'shish')
@section('content')
{{--    <div class="page-body">--}}
{{--        <div class="container mt-5">--}}
{{--            <div class="col-12 grid-margin stretch-card">--}}
{{--                <div class="card">--}}
{{--                    <div class="card-body">--}}
{{--                        <h4 class="card-title">Fan yo'nalishini</h4>--}}
{{--                            <form action="{{route('sciens.store')}}" method="post" class="forms-sample">--}}
{{--                                @csrf--}}
{{--                                <div class="form-group">--}}
{{--                                    <label for="exampleInputName1">Nomi</label>--}}
{{--                                    <input name="sciensName" type="text" class="form-control" id="exampleInputName1" placeholder="Fan yo'nalishi nomi">--}}
{{--                                    <span class="text-danger">@error('sciensName'){{ $message }} @enderror</span>--}}
{{--                                </div>--}}
{{--                                <button type="submit" class="btn btn-gradient-primary me-2">Qo'shish</button>--}}
{{--                            </form>--}}
{{--                    </div>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
<div class="page-body">
    <div class="row">
        <div class="col-sm-12 m-auto mt-5">
            <div class="card">
                <div class="card-header">
                    <h5>Yo'nalish yaratish</h5>
                </div>
                <div class="card-body">
                    <form id="formTaq" class="theme-form" method="post" action="{{route('sciens.store')}}">
                        @csrf
                        <div class="mb-3">
                            <label class="col-form-label pt-0" for="exampleInputEmail1">Yo'nalish nomi</label>
                            <input name="sciensName" class="form-control" id="exampleInputEmail1" type="text" aria-describedby="emailHelp" placeholder="Yo'nalish nomi">
                            <span class="text-danger">@error('sciensName'){{ $message }} @enderror</span>
                        </div>
                        <div class="mb-3">
                            <input type="submit" class="btn btn-primary" value="Yo'nalish yaratish"/>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>

</div>
@endsection

resources/views/admin/sciens/edit.blade.php
@extends('admin.layouts.master')
@section('title', 'Yo\'nalishni o\'zgartirish')
@section('content')

    <div class="page-body">
        <div class="row">
            <div class="col-sm-12 m-auto mt-5">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Jurnal nomini tahrirlash</h4>
                    </div>
                    <div class="card-body">
                        <form class="forms-sample" action="{{route('sciens.update', $scien)}}" method="POST">
                            @csrf
                            @method('PUT')
                            <div class="mb-3 form-group">
                                <label for="exampleInputUsername1">Jurnal nomi</label>
                                <input value="{{$scien->sciensName}}" name="sciensName" type="text" class="form-control" id="exampleInputUsername1" placeholder="Yo\'nalish nomi">
                            </div>

                            <div class="mb-3">
                                <button class="btn btn-primary" type="submit">Jurnalni o'zgartirish</button>
                            </div>

                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

resources/views/admin/sciens/index.blade.php
@extends('admin.layouts.master')
@section('title','Fan yo\'nalishlari')
@section('content')

{{--    <div class="container mt-5">--}}

{{--        <div class="col-lg-12 grid-margin stretch-card">--}}

{{--            <div class="card">--}}
{{--                @if(\Illuminate\Support\Facades\Session::get('success'))--}}
{{--                    <div class="alert alert-success">--}}
{{--                        {{\Illuminate\Support\Facades\Session::get('success')}}--}}
{{--                    </div>--}}
{{--                @endif--}}
{{--                <div class="card-body">--}}
{{--                    <h4 class="card-title">Fan yo'nalishlari jadvali</h4>--}}
{{--                    <table class="table">--}}
{{--                        <thead>--}}
{{--                        <tr>--}}
{{--                            <th>№</th>--}}
{{--                            <th>Yo'nalish nomi</th>--}}
{{--                            <th>Yaratilgan vaqti</th>--}}
{{--                            <th>Tahrirlash</th>--}}
{{--                        </tr>--}}
{{--                        </thead>--}}
{{--                        <tbody>--}}
{{--                        @foreach($sciens as $scien)--}}
{{--                            <tr>--}}
{{--                                <td>{{$loop->index+1}}</td>--}}
{{--                                <td>{{$scien->sciensName}}</td>--}}
{{--                                <td>{{$scien->created_at}}</td>--}}
{{--                                <td>--}}
{{--                                    <a href="{{route('sciens.edit', $scien)}}" class="d-inline-block btn btn-primary"><i class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;O'zgartirish</a>--}}
{{--                                    <form class="d-inline-block" action="{{route('sciens.destroy', $scien->id)}}" method="POST">--}}
{{--                                        @csrf--}}
{{--                                        @method('DELETE')--}}
{{--                                        <button type="submit" class="btn btn-danger"><i class="fa-solid fa-trash-arrow-up"></i>&nbsp;&nbsp; O'chirish</button>--}}
{{--                                        <button type="submit" class="btn btn-danger show_confirm" data-toggle="tooltip" title='Delete'><i class="far fa-trash-alt"></i>&nbsp;&nbsp;O'chirish</button>--}}

{{--                                    </form>--}}
{{--                                </td>--}}
{{--                            </tr>--}}
{{--                        @endforeach--}}
{{--                        </tbody>--}}
{{--                    </table>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}
<br><br>
<div class="page-body">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    <div class="card-header">
                        <h5>Jurnallar ro'yxati</h5><span>Use a class<code>table</code> to any table.</span>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th scope="col">№</th>
                                <th scope="col">Jurnal nomi</th>
                                <th scope="col">Jurnal yaratilgan vaqti</th>
                                <th scope="col">Tahrirlash</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($sciens as $scien)
                                <tr>
                                    <th>{{$loop->index+1}}</th>
                                    <td>{{$scien->sciensName}}</td>
                                    <td>{{$scien->created_at}}</td>
                                    <td>
                                        <a href="{{route('sciens.edit', $scien)}}"
                                           class="d-inline-block btn btn-primary"><i
                                                class="fa-solid fa-pen-to-square"></i>&nbsp;&nbsp;O'zgartirish</a>
                                        <form class="d-inline-block" action="{{route('sciens.destroy', $scien->id)}}"
                                              method="POST">
                                            @csrf
                                            @method('DELETE')

                                            <button type="submit" class="btn btn-danger show_confirm"
                                                    data-toggle="tooltip" title='Delete'><i
                                                    class="far fa-trash-alt"></i>&nbsp;&nbsp;O'chirish
                                            </button>

                                        </form>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>
{{--                        <div>{{ ($sciens->count() > 0) ? $sciens->links() : '' }}</div>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection
@push('script')
    <script type="text/javascript">

        $('.show_confirm').click(function(event) {
            var form =  $(this).closest("form");
            var name = $(this).data("name");
            event.preventDefault();
            swal({
                title: `Siz yo\'nalishni o\'chirmoqchimisiz?`,
                // text: "If you delete this, it will be gone forever.",
                icon: "warning",
                buttons: true,
                dangerMode: true,
            })
                .then((willDelete) => {
                    if (willDelete) {
                        form.submit();
                    }
                });
        });

    </script>
@endpush

resources/views/admin/sciens/success.blade.php
@extends('admin.layouts.master')
@section('title','Xabarlar')
@section('content')
    {{--    <div class="container mt-5">--}}

    {{--        <div class="col-lg-12 grid-margin stretch-card">--}}

    {{--            <div class="card">--}}
    {{--                @if(\Illuminate\Support\Facades\Session::get('success'))--}}
    {{--                    <div class="alert alert-success">--}}
    {{--                        {{\Illuminate\Support\Facades\Session::get('success')}}--}}
    {{--                    </div>--}}
    {{--                @endif--}}
    {{--                <div class="card-body">--}}
    {{--                    <h4 class="card-title">Tasdiqlangan maqolalar</h4>--}}
    {{--                    <table class="table">--}}
    {{--                        <thead>--}}
    {{--                        <tr>--}}
    {{--                            <th>№</th>--}}
    {{--                            <th>Yuborgan shaxs</th>--}}
    {{--                            <th>Maqola Soni</th>--}}
    {{--                            <th>Yuborilgan vaqti</th>--}}
    {{--                            <th>doc fayl</th>--}}
    {{--                            <th>pdf fayl</th>--}}
    {{--                            <th>taqriz fayl</th>--}}
    {{--                            <th>Tasdiqlash</th>--}}
    {{--                        </tr>--}}
    {{--                        </thead>--}}
    {{--                        <tbody>--}}

{{--                            @foreach($articles as $article)--}}
{{--                                    @if($maqolas->show_date <= date('Y-m-d', time()))--}}
{{--                                    @if($article->file != null)--}}
{{--                                        <tr>--}}
{{--                                            <td>{{$loop->index+1}}</td>--}}
{{--                                            <td>{{$article->users->lname." ".$article->users->name}}</td>--}}
{{--                                            <td>{{$article->publication}}</td>--}}
{{--                                            <td>{{substr($article->created_at,0,10)}}</td>--}}
{{--                                            <td>--}}
{{--                                                <a href="{{asset('files/'.$article->docFormat)}}" class="btn btn-sm btn-primary" type="button" data-bs-toggle="tooltip" title="btn btn-primary"><i class="fa fa-download"></i>&nbsp;&nbsp;DOC</a>--}}
{{--                                            </td>--}}
{{--                                            <td>--}}
{{--                                                <a href="{{asset('files/'.$article->pdfFormat)}}" class="btn btn-sm btn-danger" type="button" data-bs-toggle="tooltip" title="btn btn-secondary"><i class="fa fa-download"></i>&nbsp;&nbsp;PDF</a>--}}
{{--                                            </td>--}}
{{--                                            <td>--}}
{{--                                                <a href="{{asset('files/'.$article->taqriz)}}"    class="btn btn-sm btn-warning" type="button" data-bs-toggle="tooltip" title="btn btn-info"><i class="fa fa-download"></i>&nbsp;&nbsp;Taqriz</a>--}}
{{--                                            </td>--}}
{{--                                        </tr>--}}
{{--                                    @endif--}}
{{--                            @endforeach--}}
    {{--                        </tbody>--}}
{{--                            <div>{{ ($articles->count() > 0) ? $articles->links() : '' }}</div>--}}
    {{--                    </table>--}}
    {{--                </div>--}}
    {{--            </div>--}}
    {{--        </div>--}}
    {{--    </div>--}}

    <div class="page-body pt-4">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        @if(\Illuminate\Support\Facades\Session::get('success'))
                            <div class="alert alert-success">
                                {{\Illuminate\Support\Facades\Session::get('success')}}
                            </div>
                        @endif
                        <div class="card-header">
                            <h4 class="card-title">Tasdiqlangan maqolalar</h4>
                        </div>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th>№</th>
                                    <th>Yuborgan shaxs</th>
                                    <th>Maqola Soni</th>
                                    <th>Yuborilgan vaqti</th>
                                    <th>doc fayl</th>
                                    <th>pdf fayl</th>
                                    <th>taqriz fayl</th>
                                    <th>Tasdiqlash</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($articles as $article)
                                    @if($maqolas->show_date <= date('Y-m-d', time()))
                                        @if($article->file != null)
                                            <tr>
                                                <td>{{$loop->index+1}}</td>
                                                <td>{{$article->users->lname." ".$article->users->name}}</td>
                                                <td>{{$article->publication}}</td>
                                                <td>{{substr($article->created_at,0,10)}}</td>
                                                <td>
                                                    <a href="{{asset('files/'.$article->docFormat)}}" class="btn btn-sm btn-primary" type="button" data-bs-toggle="tooltip" title="btn btn-primary"><i class="fa fa-download"></i>&nbsp;&nbsp;DOC</a>
                                                </td>
                                                <td>
                                                    <a href="{{asset('files/'.$article->pdfFormat)}}" class="btn btn-sm btn-danger" type="button" data-bs-toggle="tooltip" title="btn btn-secondary"><i class="fa fa-download"></i>&nbsp;&nbsp;PDF</a>
                                                </td>
                                                <td>
                                                    <a href="{{asset('files/'.$article->taqriz)}}"    class="btn btn-sm btn-warning" type="button" data-bs-toggle="tooltip" title="btn btn-info"><i class="fa fa-download"></i>&nbsp;&nbsp;Taqriz</a>
                                                </td>
                                            </tr>
                                        @endif
                                        @endif
                                        @endforeach
                                </tbody>
                                <div>{{ ($articles->count() > 0) ? $articles->links() : '' }}</div>
                            </table>
                            {{--<div>{{ ($sciens->count() > 0) ? $sciens->links() : '' }}</div>--}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/sciens/timesuccess.blade.php
@extends('admin.layouts.master')
@section('title','Xabarlar')
@section('content')
{{--    <div class="container mt-5">--}}

{{--        <div class="col-lg-12 grid-margin stretch-card">--}}

{{--            <div class="card">--}}
{{--                @if(\Illuminate\Support\Facades\Session::get('success'))--}}
{{--                    <div class="alert alert-success">--}}
{{--                        {{\Illuminate\Support\Facades\Session::get('success')}}--}}
{{--                    </div>--}}
{{--                @endif--}}
{{--                <div class="card-body">--}}
{{--                    <h4 class="card-title">Tasdiqlangan maqolalar</h4>--}}
{{--                    <table class="table">--}}
{{--                        <thead>--}}
{{--                        <tr>--}}
{{--                            <th>№</th>--}}
{{--                            <th>Yuborgan shaxs</th>--}}
{{--                            <th>Maqola Soni</th>--}}
{{--                            <th>Yuborilgan vaqti</th>--}}
{{--                            <th>doc fayl</th>--}}
{{--                            <th>pdf fayl</th>--}}
{{--                            <th>taqriz fayl</th>--}}
{{--                            <th>Fayl</th>--}}
{{--                                                        <th>Tasdiqlash</th>--}}
{{--                        </tr>--}}
{{--                        </thead>--}}
{{--                        <tbody>--}}

{{--                        @foreach($articles as $article)--}}
{{--                            @if($maqolas->start_date <= date('Y-m-d', time()) && $maqolas->end_date >= date('Y-m-d', time()) && $article->publication == $maqolas->publication && $article->file == null)--}}
{{--                                <tr>--}}
{{--                                    <td>{{$loop->index+1}}</td>--}}
{{--                                    <td>{{$article->users->lname." ".$article->users->name}}</td>--}}
{{--                                    <td>{{$article->publication}}</td>--}}
{{--                                    <td>{{substr($article->created_at,0,10)}}</td>--}}
{{--                                    <td>--}}
{{--                                        <a href="{{asset('files/'.$article->docFormat)}}" class="btn btn-sm btn-primary" type="button" data-bs-toggle="tooltip" title="btn btn-primary"><i class="fa fa-download"></i>&nbsp;&nbsp;DOC</a>--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        <a href="{{asset('files/'.$article->pdfFormat)}}" class="btn btn-sm btn-danger" type="button" data-bs-toggle="tooltip" title="btn btn-secondary"><i class="fa fa-download"></i>&nbsp;&nbsp;PDF</a>--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        <a href="{{asset('files/'.$article->taqriz)}}" class="btn btn-sm btn-warning" type="button" data-bs-toggle="tooltip" title="btn btn-info"><i class="fa fa-download"></i>&nbsp;&nbsp;Taqriz</a>--}}
{{--                                    </td>--}}
{{--                                    <td>--}}
{{--                                        <a href="{{ route('user.uploadfile',$article) }}" class="btn btn-sm btn-success text-white" type="button" data-bs-toggle="tooltip"> + <i class="fa fa-file"></i></a>--}}
{{--                                    </td>--}}
{{--                                </tr>--}}
{{--                            @endif--}}
{{--                        @endforeach--}}
{{--                        </tbody>--}}
{{--                        <div>{{ ($articles->count() > 0) ? $articles->links() : '' }}</div>--}}
{{--                    </table>--}}
{{--                </div>--}}
{{--            </div>--}}
{{--        </div>--}}
{{--    </div>--}}


<div class="page-body pt-4">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-12">
                <div class="card">
                    @if(\Illuminate\Support\Facades\Session::get('success'))
                        <div class="alert alert-success">
                            {{\Illuminate\Support\Facades\Session::get('success')}}
                        </div>
                    @endif
                    <div class="card-header">
                        <h4 class="card-title">Tasdiqlangan maqolalar</h4>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>№</th>
                                <th>Yuborgan shaxs</th>
                                <th>Maqola Soni</th>
                                <th>Yuborilgan vaqti</th>
                                <th>doc fayl</th>
                                <th>pdf fayl</th>
                                <th>taqriz fayl</th>
                                <th>Fayl</th>
                                <th>Tasdiqlash</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($articles as $article)
                                @if($maqolas->start_date <= date('Y-m-d', time()) && $maqolas->end_date >= date('Y-m-d', time()) && $article->publication == $maqolas->publication && $article->file == null)
                                    <tr>
                                        <td>{{$loop->index+1}}</td>
                                        <td>{{$article->users->lname." ".$article->users->name}}</td>
                                        <td>{{$article->publication}}</td>
                                        <td>{{substr($article->created_at,0,10)}}</td>
                                        <td>
                                            <a href="{{asset('files/'.$article->docFormat)}}" class="btn btn-sm btn-primary" type="button" data-bs-toggle="tooltip" title="btn btn-primary"><i class="fa fa-download"></i>&nbsp;&nbsp;DOC</a>
                                        </td>
                                        <td>
                                            <a href="{{asset('files/'.$article->pdfFormat)}}" class="btn btn-sm btn-danger" type="button" data-bs-toggle="tooltip" title="btn btn-secondary"><i class="fa fa-download"></i>&nbsp;&nbsp;PDF</a>
                                        </td>
                                        <td>
                                            <a href="{{asset('files/'.$article->taqriz)}}" class="btn btn-sm btn-warning" type="button" data-bs-toggle="tooltip" title="btn btn-info"><i class="fa fa-download"></i>&nbsp;&nbsp;Taqriz</a>
                                        </td>
                                        <td>
                                            <a href="{{ route('user.uploadfile',$article) }}" class="btn btn-sm btn-success text-white" type="button" data-bs-toggle="tooltip"> + <i class="fa fa-file"></i></a>
                                        </td>
                                    </tr>
                                @endif
                            @endforeach
                            </tbody>
                            <div>{{ ($articles->count() > 0) ? $articles->links() : '' }}</div>
                        </table>
                        {{--<div>{{ ($sciens->count() > 0) ? $sciens->links() : '' }}</div>--}}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection