routes/web.php
<?php

use App\Http\Controllers\Admin\MessangerController;
use App\Http\Controllers\Admin\RulesController;
use App\Http\Controllers\Admin\SciensController;

use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [\App\Http\Controllers\Auth\HelloController::class,'mainboard'])->name('main');

Route::get('/widget', function () {
    return view('main.pages.widget');
})->name('main.widget');

Route::get('/show_messenger/{publication}/{year}', [MessangerController::class, 'show_accept_messenger'])->name('show_messenger');

Route::resource('/messanger', MessangerController::class);


Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'isAdmin', 'preventBack']], function () {
    Route::get('/', function () {
        return view('admin.layouts.index');
    })->name("admin.dashboard");
    Route::resource('/sciens', SciensController::class);
    Route::resource('/rules', RulesController::class);
    Route::get('/notifications', [UserController::class, 'notifications'])->name('user.notifications');
    Route::get('/success', [UserController::class, 'indexsuccess'])->name('user.success');
    Route::get('/timesuccess', [UserController::class, 'timesuccess'])->name('user.timesuccess');
    Route::get('/uploadfile/{article}', [UserController::class, 'uploadFile'])->name('user.uploadfile');
    Route::put('/uploadfilestore/{article}', [UserController::class, 'uploadFileStore'])->name('user.uploadfilestore');
    Route::resource('/maqolas', \App\Http\Controllers\Admin\MaqolaController::class);
    Route::resource('/direct', \App\Http\Controllers\Admin\DirectController::class);
});

Route::group(['prefix' => 'user', 'middleware' => ['auth', 'isUser', 'preventBack']], function () {
    Route::get('/',[\App\Http\Controllers\Auth\HelloController::class, 'userboard'])->name("user.dashboard")->middleware('verified');
    Route::get('user/setting', [\App\Http\Controllers\Auth\HelloController::class, 'setting'])->name('user.setting');
    Route::put('user/edit', [\App\Http\Controllers\Auth\HelloController::class, 'userEdit'])->name('user.edit');
    Route::get('/subscription', function () {
        return view('users.profil.subscription');
    })->name('user.subscription');
    Route::resource('/articles', UserController::class);
    Route::post('/journal/section', [UserController::class, 'get_directs'])->name('ajax.journal');

});

Route::middleware(['middleware' => 'preventBack'])->group(function () {
    Auth::routes([
        'verify'=>true
    ]);
});
Route::any('/handle/{paysys}',function($paysys){
    (new Goodoneuz\PayUz\PayUz)->driver($paysys)->handle();
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, HasFactory, Notifiable, \Illuminate\Auth\MustVerifyEmail;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'lname',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/User/RegController.php
<?php

namespace App\Http\Controllers\Auth;

use App\Domain\Articles\Models\Article;
use App\Domain\Articles\Repositories\ArticleRepositories;
use App\Domain\Rules\Repositories\RulesRepositories;
use App\Http\Controllers\Controller;
use App\Models\RegisterModel;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class RegController extends Controller
{
    function login()
    {
        return view('auth.login');
    }
    function register()
    {
        return view('auth.register');
    }
    function save(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'lname'=>'required',
            'email'=>'required|email',
            'password'=>'required|min:5|max:12',
            'password_confirm'=>'required|min:5|max:12'
        ]);
        $user = new User();
        $user->name = $request->name;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->role = 0;
        $pass1 = $request->password;
        $pass2 = $request->password_confirm;
        if ($pass1==$pass2)
        {
            $user->password = Hash::make($request->password);
            $save = $user->save();

            if ($save){
                return back()->with('success','Siz ro\'yxatdan muvofaqqiyatli o\'tdingiz!');
            }else{
                return back()->with('fail','Ro\'yxatdan o\'tishda xatolik!');
            }
        }else{
            return back()->with('fail','Parollar mos emas! Iltimos parollarni tekshirib qayta kiriting');
        }

    }

    function check(Request $request)
    {
//        dd("salom");
        $request->validate([
            'email'=>'required',
            'password'=>'required'
        ]);

        $userInfo = User::where('email','=',$request->email)->first();
        if (!$userInfo)
        {
            return back()->with('fail','Siz pochta manzilingizni xato kiritdingiz! Tekshirib qayta kiriting');
        }else{
            if (Hash::check($request->password, $userInfo->password))
            {

                $data = collect([$userInfo->id,$userInfo->name,$userInfo->lname,$userInfo->role]);
//                Session::put('logged', $data);

                if ($userInfo->role == 1)
                {
                    return redirect()->route('auth.dashboard');
                }elseif ($userInfo->role == 0)
                {
                    return redirect()->route('auth.userboard');
                }

            }else{
                return back()->with('fail','Siz parolingizni xato kiritdingiz! Tekshirib qayta kiriting');
            }
        }
    }

    function dashboard()
    {
//        if (Session::get('logged')[3]==1)
//        {
        $count_notifications = Article::where('status','=','0')->count();
        $all_notifications = Article::where('status','=','0')->get();
        return view('admin.layouts.master', compact('count_notifications','all_notifications'));
//        }else{
//            return redirect()->back();
//        }

    }
    function userboard(RulesRepositories $repositories)
    {

//        if (Session::get('logged')[3]==0)
//        {
        $rules = $repositories->getAll();
        return view('users.layouts.index', compact('rules'));
//        }else{
//            return redirect()->back();
//        }

    }

    function setting()
    {
//        if (Session::get('logged')[3]==0) {
        $user_id = Session::get('logged')[0];
        $userProfil = User::where('id', '=', $user_id)->first();
        return view('users.profil.edit', compact('userProfil'));
//        }else{
//            return redirect()->back();
//        }
    }
    function userEdit(Request $request)
    {
//        if (Session::get('logged')[3]==0) {
        $request->validate([
            'name'=>'required',
            'lname'=>'required',
            'email'=>'required|email',
            'old_pass'=>'required|min:5|max:12',
            'new_pass'=>'required|min:5|max:12',
            'new_pass_con'=>'required|min:5|max:12'
        ]);

        $user_id = Session::get('logged')[0];
        $userProfil = User::where('id','=',$user_id)->first();
        //        dd($userProfil);
        if (Hash::check($request->old_pass, $userProfil->password)){
            if ($request->new_pass == $request->new_pass_con)
            {

                $userProfil->update([
                    'name'=>$request->name,
                    'lname'=>$request->lname,
                    'email'=>$request->email,
                    'password'=>Hash::make($request->new_pass)
                ]);
                $data = collect([$userProfil->id, $userProfil->name, $userProfil->lname]);
                Session::put('logged', $data);
                return redirect()->route('auth.userboard');
            }else{
                return back()->with('fail','Parollar mos emas! Iltimos parollarni tekshirib qayta kiriting');
            }
        }else{
            return back()->with('fail','Eski parolni xato kiritdingiz! Iltimos tekshirib qayta kiriting');
        }


//        }else{
//            return redirect()->back();
//        }

    }


}

app/Http/Controllers/User/RegisterController.php
<?php

namespace App\Http\Controllers\Auth;

use App\Domain\Articles\Models\Article;
use App\Domain\Articles\Repositories\ArticleRepositories;
use App\Domain\Rules\Repositories\RulesRepositories;
use App\Http\Controllers\Controller;
use App\Models\RegisterModel;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Session;

class RegisterController extends Controller
{
    function login()
    {
        return view('auth.login');
    }
    function register()
    {
        return view('auth.register');
    }
    function save(Request $request)
    {
        $request->validate([
            'name'=>'required',
            'lname'=>'required',
            'email'=>'required|email',
            'password'=>'required|min:5|max:12',
            'password_confirm'=>'required|min:5|max:12'
        ]);
        $user = new User();
        $user->name = $request->name;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->role = 0;
        $pass1 = $request->password;
        $pass2 = $request->password_confirm;
        if ($pass1==$pass2)
        {
            $user->password = Hash::make($request->password);
            $save = $user->save();

            if ($save){
                return back()->with('success','Siz ro\'yxatdan muvofaqqiyatli o\'tdingiz!');
            }else{
                return back()->with('fail','Ro\'yxatdan o\'tishda xatolik!');
            }
        }else{
            return back()->with('fail','Parollar mos emas! Iltimos parollarni tekshirib qayta kiriting');
        }

    }

    function check(Request $request)
    {
//        dd("salom");
        $request->validate([
            'email'=>'required',
            'password'=>'required'
        ]);

        $userInfo = User::where('email','=',$request->email)->first();
        if (!$userInfo)
        {
            return back()->with('fail','Siz pochta manzilingizni xato kiritdingiz! Tekshirib qayta kiriting');
        }else{
            if (Hash::check($request->password, $userInfo->password))
            {

                $data = collect([$userInfo->id,$userInfo->name,$userInfo->lname,$userInfo->role]);
//                Session::put('logged', $data);

                if ($userInfo->role == 1)
                {
                    return redirect()->route('auth.dashboard');
                }elseif ($userInfo->role == 0)
                {
                    return redirect()->route('auth.userboard');
                }

            }else{
                return back()->with('fail','Siz parolingizni xato kiritdingiz! Tekshirib qayta kiriting');
            }
        }
    }

    function dashboard()
    {
//        if (Session::get('logged')[3]==1)
//        {
            $count_notifications = Article::where('status','=','0')->count();
            $all_notifications = Article::where('status','=','0')->get();
            return view('admin.layouts.master', compact('count_notifications','all_notifications'));
//        }else{
//            return redirect()->back();
//        }

    }
    function userboard(RulesRepositories $repositories)
    {

//        if (Session::get('logged')[3]==0)
//        {
            $rules = $repositories->getAll();
            return view('users.layouts.index', compact('rules'));
//        }else{
//            return redirect()->back();
//        }

    }

    function setting()
    {
//        if (Session::get('logged')[3]==0) {
            $user_id = Session::get('logged')[0];
            $userProfil = User::where('id', '=', $user_id)->first();
            return view('users.profil.edit', compact('userProfil'));
//        }else{
//            return redirect()->back();
//        }
    }
    function userEdit(Request $request)
    {
//        if (Session::get('logged')[3]==0) {
            $request->validate([
                'name'=>'required',
                'lname'=>'required',
                'email'=>'required|email',
                'old_pass'=>'required|min:5|max:12',
                'new_pass'=>'required|min:5|max:12',
                'new_pass_con'=>'required|min:5|max:12'
            ]);

            $user_id = Session::get('logged')[0];
            $userProfil = User::where('id','=',$user_id)->first();
            //        dd($userProfil);
            if (Hash::check($request->old_pass, $userProfil->password)){
                if ($request->new_pass == $request->new_pass_con)
                {

                    $userProfil->update([
                        'name'=>$request->name,
                        'lname'=>$request->lname,
                        'email'=>$request->email,
                        'password'=>Hash::make($request->new_pass)
                    ]);
                    $data = collect([$userProfil->id, $userProfil->name, $userProfil->lname]);
                    Session::put('logged', $data);
                    return redirect()->route('auth.userboard');
                }else{
                    return back()->with('fail','Parollar mos emas! Iltimos parollarni tekshirib qayta kiriting');
                }
            }else{
                return back()->with('fail','Eski parolni xato kiritdingiz! Iltimos tekshirib qayta kiriting');
            }


//        }else{
//            return redirect()->back();
//        }

    }


}

resources/views/users/layouts/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12 footer-copyright text-center">
                <p class="mb-0">Buxoro 2021 © Buxoro Davlat Universiteti </p>
            </div>
        </div>
    </div>
</footer>

resources/views/users/layouts/index.blade.php
@extends('users.layouts.master')
@section('title','Shaxsiy profil')
@section('content')
    <div class="page-body">
        <div class="container-fluid">
            <div class="page-title">
                <div class="row">
                    <div class="col-6">
                        <!-- <h3>Sample Page</h3> -->
                    </div>
                    <div class="col-6">
                        <ol class="breadcrumb">
{{--                            <li class="breadcrumb-item"><a href="index.html">                                       <i data-feather="home"></i></a></li> -->--}}
{{--                             <li class="breadcrumb-item">Pages</li>--}}
{{--                             <li class="breadcrumb-item active">Sample Page</li>--}}
                        </ol>
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid starts-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                    @foreach($rules as $rule)
                        <div class="card-header">
                            <label class="badge badge-danger f-22">Umumiy qoidalar</label><h3>{{$rule->title}}</h3>
                        </div>
                        <div class="card-body" style="text-align: justify">
                            <p>{{$rule->description}}</p>
                        </div>
                    @endforeach
                    </div>
                </div>
            </div>
        </div>
        <!-- Container-fluid Ends-->
    </div>
@endsection

resources/views/users/layouts/navbar.blade.php
<div class="page-header">
    <div class="header-wrapper row m-0">
        <form class="form-inline search-full col" action="#" method="get">
            <div class="form-group w-100">
                <div class="Typeahead Typeahead--twitterUsers">
                    <div class="u-posRelative">
                        <input class="demo-input Typeahead-input form-control-plaintext w-100" type="text" placeholder="Search Cuba .." name="q" title="" autofocus>
                        <div class="spinner-border Typeahead-spinner" role="status"><span class="sr-only">Loading...</span></div><i class="close-search" data-feather="x"></i>
                    </div>
                    <div class="Typeahead-menu"></div>
                </div>
            </div>
        </form>
        <div class="header-logo-wrapper col-auto p-0">
            <div class="logo-wrapper"><a href=""><img class="img-fluid" src="{{asset('users/assets/images/logo/logo.png')}}" alt=""></a></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="align-center"></i></div>
        </div>
        <div class="left-header col horizontal-wrapper ps-0">
            <ul class="horizontal-menu">
                <li class="mega-menu outside"><a class="nav-link" href="#!"><i data-feather="layers"></i><span>Bonus Ui</span></a>

                </li>
                <li class="level-menu outside"><a class="nav-link" href="#!"><i data-feather="inbox"></i><span>Level Menu</span></a>

                </li>
            </ul>
        </div>
        <div class="nav-right col-8 pull-right right-header p-0">
            <ul class="nav-menus">

                <li class="onhover-dropdown">
                    <div class="notification-box"><i data-feather="bell"> </i><span class="badge rounded-pill badge-secondary">4                                </span></div>
                    <ul class="notification-dropdown onhover-show-div">
                        <li><i data-feather="bell"></i>
                            <h6 class="f-18 mb-0">Notitications</h6>
                        </li>
                        <li>
                            <p><i class="fa fa-circle-o me-3 font-primary"> </i>Delivery processing <span class="pull-right">10 min.</span></p>
                        </li>
                        <li>
                            <p><i class="fa fa-circle-o me-3 font-success"></i>Order Complete<span class="pull-right">1 hr</span></p>
                        </li>
                        <li>
                            <p><i class="fa fa-circle-o me-3 font-info"></i>Tickets Generated<span class="pull-right">3 hr</span></p>
                        </li>
                        <li>
                            <p><i class="fa fa-circle-o me-3 font-danger"></i>Delivery Complete<span class="pull-right">6 hr</span></p>
                        </li>
                        <li><a class="btn btn-primary" href="#">Check all notification</a></li>
                    </ul>
                </li>

                <li>
                    <div class="mode"><i class="fa fa-moon-o"></i></div>
                </li>

                <li class="onhover-dropdown"><i data-feather="message-square"></i>
                    <ul class="chat-dropdown onhover-show-div">
                        <li><i data-feather="message-square"></i>
                            <h6 class="f-18 mb-0">Xabarlar</h6>
                        </li>
                        <li>
                            <div class="media"><img class="img-fluid rounded-circle me-3" src="{{asset('users/assets/images/user.jpg')}}" alt="">
                                <div class="status-circle online"></div>
                                <a href="{{route('messanger.index')}}">
                                <div class="media-body"><span>Nashriyot administratori</span>
                                    <p>Lorem Ipsum is simply dummy...</p>
                                </div>
                                <p class="f-12 font-success">58 mins ago</p>
                                </a>
                            </div>
                        </li>

                        <li class="text-center"> <a class="btn btn-primary" href="#">View All     </a></li>
                    </ul>
                </li>
                <li class="maximize"><a class="text-dark" href="#!" onclick="javascript:toggleFullScreen()"><i data-feather="maximize"></i></a></li>
                <li class="profile-nav onhover-dropdown p-0 me-0">
                    <div class="media profile-media"><img class="b-r-10" src="{{asset('users/assets/images/dashboard/profile.jpg')}}" alt="">
                        <div class="media-body"><span>{{\Illuminate\Support\Facades\Auth::user()->name ? \Illuminate\Support\Facades\Auth::user()->name : '' }}</span>
                            <p class="mb-0 font-roboto">{{\Illuminate\Support\Facades\Auth::user()->lname ? \Illuminate\Support\Facades\Auth::user()->lname : ''}} <i class="middle fa fa-angle-down"></i></p>
                        </div>
                    </div>
                    <ul class="profile-dropdown onhover-show-div">
                        <li><a href="{{route('user.setting')}}"><i data-feather="settings"></i><span>Sozlamalar</span></a></li>
                        <li><a style="padding: 4px 0" class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                <i data-feather="log-out"></i> Chiqish </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="post" class="d-none">
                                @csrf
                            </form>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
        <script class="result-template" type="text/x-handlebars-template">
            <div class="ProfileCard u-cf">
            <div class="ProfileCard-avatar"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-airplay m-0"><path d="M5 17H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2v10a2 2 0 0 1-2 2h-1"></path><polygon points="12 15 17 21 7 21 12 15"></polygon></svg></div>
            <div class="ProfileCard-details">
            <div class="ProfileCard-realName"></div>
            </div>
            </div>
          </script>
        <script class="empty-template" type="text/x-handlebars-template"><div class="EmptyMessage">Your search turned up 0 results. This most likely means the backend is down, yikes!</div></script>
    </div>
</div>

resources/views/users/layouts/sidebar.blade.php
<div class="sidebar-wrapper">
    <div>
        <div class="logo-wrapper"><a href="{{route('user.dashboard')}}"><img class="img-fluid for-light" src="{{asset('users/assets/images/logo/logo.png')}}" alt=""><img class="img-fluid for-dark" src="{{asset('users/assets/images/logo/logo_dark.png')}}" alt=""></a>
            <div class="back-btn"><i class="fa fa-angle-left"></i></div>
            <div class="toggle-sidebar"><i class="status_toggle middle sidebar-toggle" data-feather="grid"> </i></div>
        </div>
        <div class="logo-icon-wrapper"><a href="index.html"><img class="img-fluid" src="{{asset('users/assets/images/logo/logo-icon.png')}}" alt=""></a></div>
        <nav class="sidebar-main">
            <div class="left-arrow" id="left-arrow"><i data-feather="arrow-left"></i></div>
            <div id="sidebar-menu">
                <ul class="sidebar-links" id="simple-bar">
                    <li class="back-btn"><a href="index.html"><img class="img-fluid" src="{{asset('users/assets/images/logo/logo-icon.png')}}" alt=""></a>
                        <div class="mobile-back text-end"><span>Back</span><i class="fa fa-angle-right ps-2" aria-hidden="true"></i></div>
                    </li>
                    <li class="sidebar-main-title">
                        <div>
                            <h6 class="">Mjournal</h6>
                            <p class="">Buxoro Davlat Universiteti</p>
                        </div>
                    </li>

                    <li class="sidebar-list"><label class="badge badge-danger">Yangi</label><a class="sidebar-link sidebar-title link-nav" href="{{route('articles.create')}}"><i style="color: {{request()->is('user/articles/create') ? '#7366ff' : ''}}" data-feather="send"> </i><span style="color: {{request()->is('user/articles/create') ? '#7366ff' : ''}}">Maqola yuborish</span></a></li>

                    <li class="sidebar-list"><a class="sidebar-link sidebar-title link-nav" href="{{route('articles.index')}}"><i style="color: {{request()->is('user/articles') ? '#7366ff' : ''}}" data-feather="archive"> </i><span style="color: {{request()->is('user/articles') ? '#7366ff' : ''}}">Yuborilgan maqolalar</span></a></li>
                    <li class="sidebar-list"><label class="badge badge-success">Hoziroq</label><a class="sidebar-link sidebar-title link-nav" href="{{ route('user.subscription') }}"><i style="color: {{request()->is('user/subscription') ? '#7366ff' : ''}}" data-feather="check-square"> </i><span style="color: {{request()->is('user/subscription') ? '#7366ff' : ''}}">Obuna bo'lish</span></a></li>
                </ul>
            </div>
            <div class="right-arrow" id="right-arrow"><i data-feather="arrow-right"></i></div>
        </nav>
    </div>
</div>